#!/bin/bash
export HTTP_PROXY="http://127.0.0.1:8081"
export HTTPS_PROXY="http://127.0.0.1:8081"
export SSL_CERT_FILE="$HOME/.mitmproxy/mitmproxy-ca-cert.pem"
exec ~/Downloads/Antigravity/antigravity --no-sandbox "$@"
